name: CI workflow

on: pull_request

jobs:
  ci-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'modulo5-testing/lab-test'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Tests
        run: npm test